backend:
  name: github
  repo: foopod/docs-example
media_folder: docs/.vuepress/static/images
public_folder: /images
collections:
  - name: releases
    label: Releases
    folder: docs/releases
    path: '{{slug}}'
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
site_url: https://soft-licorice-1397a5.netlify.app
display_url: https://soft-licorice-1397a5.netlify.app